# Generated by Django 5.1.6 on 2025-03-03 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='textbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('year', models.IntegerField(max_length=4)),
                ('edition', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('course_code', models.CharField(max_length=255)),
                ('availability', models.BooleanField(default=True)),
            ],
        ),
    ]
