# Generated by Django 5.1.6 on 2025-03-03 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbooks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textbook',
            old_name='availability',
            new_name='is_available',
        ),
        migrations.AlterField(
            model_name='textbook',
            name='year',
            field=models.IntegerField(),
        ),
    ]
